export { default as BrightnessIcon } from '@mui/icons-material/Brightness6'
export { default as InfoIcon } from '@mui/icons-material/InfoOutlined'
export { default as Layers } from '@mui/icons-material/Layers'
export { default as MenuIcon } from '@mui/icons-material/Menu'

export { ArcherIcon } from './Archer'
export { CodeStatsIcon } from './CodeStats'
export { DiscordIcon } from './Discord'
export { FacebookIcon } from './Facebook'
export { GitHubIcon } from './GitHub'
export { GraphIcon } from './Graph'
export { InstagramIcon } from './Instagram'
export { VKIcon } from './VK'
